<?php
/**
 * OrderParcelStatusType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YandexMarketApi\Model;
use \YandexMarketApi\ObjectSerializer;

/**
 * OrderParcelStatusType Class Doc Comment
 *
 * @category Class
 * @description {% note alert %}  Поле устарело и не рекомендуется к использованию.  {% endnote %}  Статус заказа в партнерской службе доставки.  * &#x60;NEW&#x60; — новый.  * &#x60;CREATED&#x60; — создан в службе доставки.  * &#x60;READY_TO_SHIP&#x60; — посылка готова к передаче в службу доставки.  * &#x60;ERROR&#x60; — ошибка создания заказа.  * &#x60;UNKNOWN&#x60; — неизвестный статус.
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderParcelStatusType
{
    /**
     * Possible values of this enum
     */
    public const _NEW = 'NEW';

    public const CREATED = 'CREATED';

    public const READY_TO_SHIP = 'READY_TO_SHIP';

    public const ERROR = 'ERROR';

    public const UNKNOWN = 'UNKNOWN';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_NEW,
            self::CREATED,
            self::READY_TO_SHIP,
            self::ERROR,
            self::UNKNOWN
        ];
    }
}


