<?php
/**
 * ReturnDecisionSubreasonType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YandexMarketApi\Model;
use \YandexMarketApi\ObjectSerializer;

/**
 * ReturnDecisionSubreasonType Class Doc Comment
 *
 * @category Class
 * @description Детали причин возврата:   * &#x60;DO_NOT_FIT&#x60;:     * &#x60;USER_DID_NOT_LIKE&#x60; — товар не понравился.     * &#x60;USER_CHANGED_MIND&#x60; — передумал покупать.     * &#x60;DELIVERED_TOO_LONG&#x60; — длительный срок доставки, поэтому передумал.    * &#x60;BAD_QUALITY&#x60;:     * &#x60;BAD_PACKAGE&#x60; — упаковка товара была нарушена.     * &#x60;DAMAGED&#x60; — царапины, сколы.     * &#x60;NOT_WORKING&#x60; — не включается / не работает.     * &#x60;INCOMPLETENESS&#x60; — некомплект (не хватает детали в наборе, к товару).    * &#x60;WRONG_ITEM&#x60;:     * &#x60;WRONG_ITEM&#x60; — не тот товар.     * &#x60;WRONG_COLOR&#x60; — не соответствует по цвету.     * &#x60;DID_NOT_MATCH_DESCRIPTION&#x60; — не соответствует заявленным характеристикам/описанию.
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReturnDecisionSubreasonType
{
    /**
     * Possible values of this enum
     */
    public const USER_DID_NOT_LIKE = 'USER_DID_NOT_LIKE';

    public const USER_CHANGED_MIND = 'USER_CHANGED_MIND';

    public const DELIVERED_TOO_LONG = 'DELIVERED_TOO_LONG';

    public const BAD_PACKAGE = 'BAD_PACKAGE';

    public const DAMAGED = 'DAMAGED';

    public const NOT_WORKING = 'NOT_WORKING';

    public const INCOMPLETENESS = 'INCOMPLETENESS';

    public const WRONG_ITEM = 'WRONG_ITEM';

    public const WRONG_COLOR = 'WRONG_COLOR';

    public const DID_NOT_MATCH_DESCRIPTION = 'DID_NOT_MATCH_DESCRIPTION';

    public const UNKNOWN = 'UNKNOWN';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::USER_DID_NOT_LIKE,
            self::USER_CHANGED_MIND,
            self::DELIVERED_TOO_LONG,
            self::BAD_PACKAGE,
            self::DAMAGED,
            self::NOT_WORKING,
            self::INCOMPLETENESS,
            self::WRONG_ITEM,
            self::WRONG_COLOR,
            self::DID_NOT_MATCH_DESCRIPTION,
            self::UNKNOWN
        ];
    }
}


