<?php
/**
 * ChatsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace YandexMarketApi\Test\Api;

use \YandexMarketApi\Configuration;
use \YandexMarketApi\ApiException;
use \YandexMarketApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ChatsApiTest Class Doc Comment
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChatsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createChat
     *
     * Создание нового чата с покупателем.
     *
     */
    public function testCreateChat()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getChatHistory
     *
     * Получение истории сообщений в чате.
     *
     */
    public function testGetChatHistory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getChats
     *
     * Получение доступных чатов.
     *
     */
    public function testGetChats()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendFileToChat
     *
     * Отправка файла в чат.
     *
     */
    public function testSendFileToChat()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendMessageToChat
     *
     * Отправка сообщения в чат.
     *
     */
    public function testSendMessageToChat()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
